INSERT INTO rooms (room_name, capacity, keywords, price, floor, room_number, room_size, equipment, permission, exceptions)
VALUES
    ('Meenete, raamatupood', 30, 'Avalik ala. Vestlusõhtud, arutelud, üritused.', 0, 1, 'AB-1106', 482.2, '', 'PÄRING', ''),
    ('Vasakpoolne fuajee', NULL, 'Avalik ala. Messid, üritused.', 0, 1, 'AB-1036', 132.8, 'Liigutatavad istumisalad', 'PÄRING', ''),
    ('Parempoolne fuajee', NULL, 'Avalik ala. Messid, üritused. Raamatukogu lahtioleku ajal peab olema üldsusele avatud.', 0, 1, 'AB-1037', NULL, 'Keskel istumisalad, infopunkt', 'PÄRING', ''),
    ('Fuajee lounge', 30, 'Avalik ala. Konverentside oote ja kohtumisala.', 0, 1, 'AB-1039', 140.4, 'Mobiilsed istumisalad', 'PÄRING', ''),
    ('Suur konverentsisaal', 300, 'Üritused', 0, 1, 'E-1603', 187.5, 'Konverentsisaali toolid', 'PÄRING', ''),
    ('Harulduste lugemissaal', NULL, '', 10, NULL, '', NULL, '', 'jah', ''),
    ('Nõupidamine', 8, 'Avalik ala. Koosolekud', 10, 2, 'AB-2201', 31.1, '8 tooli, 4 lauda, 2 nagi', 'jah', ''),
    ('Nõupidamine', 13, 'Avalik ala. Koosolekud', 5.5, 2, 'AB-2205', 33.4, '13 tooli, 6 lauda, 2 nagi', 'jah', ''),
    ('Lasteala', 50, 'Avalik ala. Haridustegevused, ürituste läbiviimine', 0, 3, 'AB-3207', 138.9, '5 ümmargust lastelauda, 25 lastepinki, u 20 istekohta trepistikul, 16 väikest tumbat, teisaldatav ekraan (+ teisaldatavad toolid)', 'EI', ''),
    ('Lugemissaali vasak ots, kaartega istumisalad)', 50, 'Avalik ala. Haridustegevused, ürituste läbiviimine', 0, 3, 'AB-3232', 300, '7 madalat lauda, 8 tugitooli, 15 istekohta kaare trepistikul, teisaldatav ekraan (+ teisaldatavad toolid)', 'EI', ''),
    ('Lugemissaali parem ots)', 50, 'Avalik ala. Haridustegevused, ürituste läbiviimine', 0, 3, 'AB-3233', 300, '7 madalat lauda, 8 tugitooli, 15 istekohta kaare trepistikul, teisaldatav ekraan (+ teisaldatavad toolid)', 'EI', ''),
    ('Õppeklass', 39, 'Haridustegevused', 20, 3, 'AB-3201', 69.8, '36 tooli, 14 lauda, 1 nutitahvel', 'jah', 'Broneeritav 16.30-20.00 ja nädalavahetused, ülejäänud aeg RaRa broneering.'),
    ('Õppeklass', 24, 'Haridustegevused', 10, 3, 'AB-3204', 73.1, '24 tooli, 12 lauda, 1 nutitahvel', 'jah', 'Broneeritav 17.30-20.00 ja nädalavahetused, ülejäänud aeg RaRa broneering. NB! Kutseõppesessioonide ajal terve nädal kinni.'),
    ('Tööruum', 8, 'Avalik ala. Grupitööd, ürituste läbiviimine (nt sünnipäevad).', 10, 3, 'AB-3208', 18.1, '8 ligipääsetavuse nõuetele vastavat tooli, 2 ligipääsetavuse nõuetele vastavat lauda, ekraan', 'jah', ''),
    ('Tööruum', 8, 'Avalik ala. Grupitööd, ürituste läbiviimine (nt sünnipäevad).', 10, 3, 'AB-3209', 16.8, '8 tooli, 3 ümarlauda, ekraan', 'jah', ''),
    ('Tööruum', 8, 'Avalik ala. Grupitööd, ürituste läbiviimine (nt sünnipäevad).', 10, 3, 'AB-3210', 16.8, '8 tooli, 3 ümarlauda, ekraan', 'jah', ''),
    ('Väike mänguruum', 4, '', 0, 3, 'AB-3211', 16.7, '4 kott-tooli, 3 ümarlauda', 'EI', ''),
    ('Vaikne lugemisala', 12, '', 0, 3, 'AB-3212', 36.4, '8 kott-tooli, 4 ümarlauda, 2 ekraani', 'EI', ''),
    ('TalTech robootikalabor', 16, 'Rühmatööd, haridustegevused', 0, 3, 'AB-3215', 71.3, '10 madalat ümarpukki, 6 tooli, 2 suurt lauda, 2 ekraani - NB! sisustus lõplikult kooskõlastamata', 'PÄRING', ''),
    ('Nõupidamine', 4, 'Avalik ala. Koosolekud', 10, 3, 'AB-3217', 12, '4 tugitooli, 1 ümarlaud, ekraan', 'jah', ''),
    ('Nõupidamine', 4, 'Avalik ala. Koosolekud', 10, 3, 'AB-3218', 12, '4 tugitooli, 1 ümarlaud, ekraan', 'jah', ''),
    ('Arvutitöökoht', 8, 'Avalik ala. Individuaaltöö', 10, 3, 'AB-3219', 104.8, '8 arvutilauda ja tooli', 'jah', ''),
    ('LvlUp', 36, 'Arvutimängud, haridustegevused', 0, 3, 'AB-3220', 70.5, '14 tugitooli, 7 konsooli, 3 arvutikohta, 15 virnastatavat plasttooli, 2 ekraani 6 tugitooli, 4 tooli, 10 konsooli, 2 arvutikohta', 'PÄRING', ''),
    ('LvlUp', 12, 'Arvutimängud, haridustegevused', 0, 3, 'A-3227', 68.9, '14 tugitooli, 7 konsooli, 3 arvutikohta, 15 virnastatavat plasttooli, 2 ekraani 6 tugitooli, 4 tooli, 10 konsooli, 2 arvutikohta', 'PÄRING', ''),
    ('Õppeklass (saab jagada kaheks ruumiks)', 36, 'Haridustegevused', 10, 3, 'AB-3221', 69.8, '36 tooli, 15 lauda, 2 nutitahvlit', 'jah', 'Broneeritav 16.30-20.00 ja nädalavahetused, ülejäänud aeg RaRa broneering.'),
    ('Õppeklass (saab liita AB-3225ga)', 18, 'Haridustegevused', 10, 3, 'AB-3222', 34.4, '13 kott-tooli, 5 diivanilauda, 4 tooli, 1 madal ümarpukk, nutitahvel', 'jah', 'Broneeritav 16.30-20.00 ja nädalavahetused, ülejäänud aeg RaRa broneering.'),
    ('Stuudio', 8, '', 0, 3, 'AB-3224', 68.4, '4 tooli, 4 madalat ümarpukki, 2 lauda', 'PÄRING', ''),
    ('Õppeklass', 36, 'Haridustegevused', 10, 3, 'AB-3225', 72.5, '36 tooli, 12 lauda, 2 nutitahvlit', 'jah', 'Broneeritav 16.30-20.00 ja nädalavahetused, ülejäänud aeg RaRa broneering.'),
    ('Arvutiklass', 14, 'Arvutid, haridustegevused', 10, 3, 'AB-3228', 34.3, '14 arvutikohta, keskel suur laud+14 madalat ümarpukki, nutitahvel', 'jah', 'Broneeritav 16.30-20.00 ja nädalavahetused, ülejäänud aeg RaRa broneering.'),
    ('Maker lab', 15, 'Individuaaltöö, rühmatööd, haridustegevused', 0, 3, 'AB-3230', 87.6, '11 madalat ümarpukki, 2 seljatoega pukki, 11 lauda', 'PÄRING', ''),
    ('Galactica, näitus', NULL, '', 10, NULL, '', NULL, '', 'EI', ''),
    ('esitluskoobas, ooteala', NULL, '', 0, NULL, '', NULL, '', 'PÄRING', ''),
    ('Teadlaste tööruum', 3, 'Teadustöö', 6, 4, 'AB-4208', 16, '2 tooli, 2 lauda, 3 monitori', 'jah', ''),
    ('Tööruum', 6, 'Grupitööd', 6, 4, 'AB-4209', 15.7, '6 tooli, 3 lauda', 'jah', ''),
    ('Tööruum', 4, 'Individuaal- või grupitöö', 6, 4, 'AB-4210', 6.6, '4 tooli, laud', 'jah', ''),
    ('Tööruum', 4, 'Individuaal- või grupitöö', 6, 4, 'AB-4211', 6.8, '4 tooli, laud', 'jah', ''),
    ('Tööruum', 4, 'Individuaal- või grupitöö', 7, 4, 'Ab-4212', 6.8, '4 tooli, laud', 'jah', ''),
    ('Tööruum', 4, 'Individuaal- või grupitöö', 8, 4, 'AB-4213', 6.8, '4 tooli, laud', 'jah', ''),
    ('Tööruum', 4, 'Individuaal- või grupitöö', 8, 4, 'AB-4214', 6.7, '4 tooli, laud', 'jah', ''),
    ('Tööruum', 4, 'Individuaal- või grupitöö', 5, 4, 'AB-4216', 6.5, '4 tooli, laud', 'jah', ''),
    ('Tööruum', 4, 'Individuaal- või grupitöö', 3, 4, 'AB-4217', 6.8, '4 tooli, laud', 'jah', ''),
    ('Tööruum', 4, 'Individuaal- või grupitöö', 4, 4, 'AB-4218', 6.8, '4 tooli, laud', 'jah', ''),
    ('Tööruum', 4, 'Individuaal- või grupitöö', 2, 4, 'AB-4219', 6.8, '4 tooli, laud', 'jah', ''),
    ('Tööruum', 4, 'Individuaal- või grupitöö', 2, 4, 'AB-4220', 6.8, '4 tooli, laud', 'jah', ''),
    ('Filmiruum', 2, 'Arhiivi filmide vaatamine', 6, 4, 'AB-4221', 15.7, 'RA ruumid - 2 tooli, laud, ekraan', 'PÄRING', ''),
    ('Filmiruum', 2, 'Arhiivi filmide vaatamine', 6, 4, 'AB-4222', 16, 'RA ruumid - 2 tooli, laud, ekraan', 'PÄRING', ''),
    ('Meediasalong', 35, 'Üritused, filmide vaatamine, koolitused, vastuvõtud', 0, 5, 'AB-5201', 130.9, '10 diivanit, 7 tugitooli, 8 tooli, 1 suur laud, 12 ümarlauda, 2 suuremat ümarlauda', 'PÄRING', ''),
    ('Ürituste ala', 24, 'Ürituste läbiviimine', 0, 5, 'AB-5204', 84.7, '24 tooli, 12 lauda, ekraan; eraldatud saalist kardinatega', 'PÄRING', ''),
    ('Tööruum', 30, 'Koolitused, töötoad', 10, 5, 'AB-5205', 37.3, '30 plasttooli, 6 lauda', 'jah', ''),
    ('Tööruum', 4, 'Individuaal- või grupitöö', 10, 5, 'AB-5206', 9.1, '4 tugitooli, 1 ümarlaud', 'jah', ''),
    ('Tööruum', 4, 'Individuaal- või grupitöö', 3, 5, 'AB-5207', 9.1, '4 tooli, laud', 'jah', ''),
    ('Tööruum', 4, 'Individuaal- või grupitöö', 5, 5, 'AB-5208', 8.9, '4 tooli, laud', 'jah', ''),
    ('Tööruum', 4, 'Individuaal- või grupitöö', 6, 5, 'AB-5209', 8.8, '4 kott-tooli, 1 laud', 'jah', ''),
    ('Vaegnägija ruum', 2, 'Individuaal- või grupitöö', 7, 5, 'AB-5210', 6.3, '2 tooli, laud', 'jah', ''),
    ('Tööruum', 2, 'Individuaaltöö', 8, 5, 'AB-5211', 4.6, '2 tooli, laud', 'jah', ''),
    ('Tööruum', 12, 'Grupitööd', 10, 5, 'AB-5212', 18.5, '12 tooli, 3 lauda', 'jah', ''),
    ('Teadlaste tööruum', 3, 'Teadustöö', 10, 5, 'AB-5213', 18.5, '1 tugitool kõrge leeniga, 2 tooli, 2 lauda, 3 monitori', 'jah', ''),
    ('Tööruum', 4, 'Individuaal- või grupitöö', 10, 5, 'AB-5214', 9.1, '4 kott-tooli, 1 ümarlaud', 'jah', ''),
    ('Tööruum', 12, 'Grupitööd', 10, 5, 'AB-5215', 18.5, '12 tooli, 3 lauda', 'NULL', ''),
    ('Tööruum', 4, 'Individuaal- või grupitöö', 10, 5, 'AB-5216', 8.8, '4 tugitooli, 1 ümarlaud', 'NULL', ''),
    ('Ürituste ala', 40, 'Ürituste läbiviimine', 0, 5, 'AB-5217', 84.6, '17 diivanit, 6 lamamistooli, 6 ümarlauda, ekraan; eraldatud saalist kardinatega', 'PÄRING', ''),
    ('Tööruum', 8, 'Grupitööd', 10, 5, 'AB-5219', 20.4, '8 tugitooli, 2 ümarlauda', 'NULL', ''),
    ('Tööruum', 8, 'Grupitööd', 10, 5, 'AB-5223', 20.5, '8 tugitooli, 2 ümarlauda', 'NULL', ''),
    ('Kabinet-reserv', 10, 'Grupitööd', 0, 6, 'AB-6126', 69.7, '4 diivanit, 4 tugitooli, 6 diivanlauda', 'PÄRING', ''),
    ('Jazzi kohvik', 66, 'Kontserdid', 0, 6, 'AB-6203', 391.5, '27 diivanit, 12 tugitooli, 24 ümarlauda, 4 teisaldatavat lava', 'PÄRING', ''),
    ('Klaver', 1, 'Klaveriõpe, klaverimäng', 10, 6, 'AB-6204', 21.6, 'klaver, klaveritool, pillimeeste abilaud', 'NULL', ''),
    ('Inspiratsioon', 5, 'Helilooming', 10, 6, 'AB-6205', 21.5, '3 kasepuidust tooli, 1 diivan, 2 pillimeeste abilauda', 'NULL', ''),
    ('Lindistusstuudio', 5, 'Helilooming', 10, 6, 'AB-6206', 28.7, '3 kasepuidust tooli, 1 diivan, 3 pillimeeste abilauda', 'NULL', ''),
    ('Terrass', NULL, 'Puhke- ja ürituste ala', 0, 6, 'AB', NULL, 'Istumisalad, õuemööbel', 'PÄRING', ''),
    ('Teatri hajuala (lisaks terrass)', 80, 'Puhke- ja ürituste ala', 0, 7, 'AB-7006', 180.9, 'Teatrikohviku mööbel', 'PÄRING', ''),
    ('Tornisaal', NULL, 'Ürituste läbiviimine', 0, 8, 'AB-8003', 246.2, 'Lava, toolid', 'PÄRING', ''),
    ('Tornisaali galerii', NULL, 'Ürituste läbiviimine', 0, 8, 'AB-8008', 123, 'Kohvikumööbel', 'PÄRING', '');